In [1]:
import io
import pandas as pd
from csv_preprocessing_functions import to_snake_case, curate_airbnb_csv_file, input_to_output_csv

In [13]:
uploaded_file_csv = 'reservations (1).csv'
uploaded_file_xslx = 'reservations (1).xlsx'
df = pd.read_excel(uploaded_file_xslx)

In [14]:
df

,Κωδικός επιβεβαίωσης,Κατάσταση,Όνομα επισκέπτη,Επικοινωνία,αριθμός ενηλίκων,αριθμός παιδιών,αριθμός βρεφών,Start date,End date,αριθμός διανυκτερεύσεων,Έγινε κράτηση,Καταχώρηση,Έσοδα
0,HMMRATDES8,Παλιός επισκέπτης,Yaren Kul Kul,+90 534 334 54 23,2,0,0,25/5/2024,29/5/2024,4,2024-05-21,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,"€ 274,40"
1,HM552YECQ8,Παλιός επισκέπτης,Philip Lambrakos,+1 832-622-7539,2,0,0,19/5/2024,25/5/2024,6,2024-04-30,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,"€ 482,36"
2,HMQDTHRDH2,Παλιός επισκέπτης,Γεωργιος Καγιας,NaN,2,0,0,17/5/2024,19/5/2024,2,2024-05-14,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,"€ 156,94"
3,HM25FZ98J9,Παλιός επισκέπτης,Egle M,NaN,1,0,0,2024-11-05 00:00:00,13/5/2024,2,2024-05-10,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,"€ 156,94"
4,HMCYZYBPWA,Παλιός επισκέπτης,Nikos Katsikis,NaN,1,0,0,25/4/2024,30/4/2024,5,2024-04-21,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,"€ 385,12"

In [17]:
df.columns = ['Confirmation Code', 'Status', 'Guest Name', 'Contact Number', 'Number of Adults', 'Number of Children', 
                  'Number of Infants', 'Start Date', 'End Date', 'Nights', 'Booked Date', 'Listing', 'Amount']        
df['Currency'] = 'EUR'

In [18]:
cols_to_keep = ['Confirmation Code', 'Status', 'Start Date', 'End Date', 'Nights', 'Booked Date', 'Guest Name', 'Contact Number', 'Listing', 'Currency', 'Amount']

In [19]:
df = df[cols_to_keep]

In [24]:
pd.to_datetime(df['Start Date']

0              25/5/2024
1              19/5/2024
2              17/5/2024
3    2024-11-05 00:00:00
4              25/4/2024
Name: Start Date, dtype: object

In [22]:
dates_cols = [ 'Start Date', 'End Date', 'Booked Date']
for col in dates_cols:
    df[col] = pd.to_datetime(df[col], dayfirst = True , format="%d/%m/%Y")

ValueError: time data '2024-11-05 00:00:00' does not match format '%d/%m/%Y' (match)

In [20]:
df

,Confirmation Code,Status,Start Date,End Date,Nights,Booked Date,Guest Name,Contact Number,Listing,Currency,Amount
0,HMMRATDES8,Παλιός επισκέπτης,25/5/2024,29/5/2024,4,2024-05-21,Yaren Kul Kul,+90 534 334 54 23,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,EUR,"€ 274,40"
1,HM552YECQ8,Παλιός επισκέπτης,19/5/2024,25/5/2024,6,2024-04-30,Philip Lambrakos,+1 832-622-7539,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,EUR,"€ 482,36"
2,HMQDTHRDH2,Παλιός επισκέπτης,17/5/2024,19/5/2024,2,2024-05-14,Γεωργιος Καγιας,NaN,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,EUR,"€ 156,94"
3,HM25FZ98J9,Παλιός επισκέπτης,2024-11-05 00:00:00,13/5/2024,2,2024-05-10,Egle M,NaN,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,EUR,"€ 156,94"
4,HMCYZYBPWA,Παλιός επισκέπτης,25/4/2024,30/4/2024,5,2024-04-21,Nikos Katsikis,NaN,Ηλιόλουστο ρετιρέ στο Παγκράτι με απεριόριστη θέα,EUR,"€ 385,12"

In [21]:
df.to_excel('mpla1.xlsx')